### ISSUE TITLE
not working with Neon.3 (4.6.3)

### ISSUE THREAD

**Issue by scouchma** [JorisAerts/Eclipse-Environment-Variables#1]
Hi,

I dropped the jar into the Dropins folder on my mac, and restarted eclipse, but no joy. :-( 

What can I send you to help determine why your plugin does not show up in my General tab?

Thanks.

Stephen

![screen shot 2017-05-24 at 12 10 54 pm](https://cloud.githubusercontent.com/assets/2279856/26413465/1a01591a-407a-11e7-8268-4bcf63f9dbc1.png)
![screen shot 2017-05-24 at 12 11 04 pm](https://cloud.githubusercontent.com/assets/2279856/26413473/1d9cd770-407a-11e7-9954-c2a9cfee9070.png)

**Comment by JorisAerts** [comment]
It's compiled using JDK8, maybe that is the problem?
