### ISSUE TITLE
Eclipse links broken

### ISSUE THREAD

**Issue by akwala** [JorisAerts/Eclipse-Environment-Variables#12]
On the README pg, the Install links and the link to the plugin's pg @ Eclipse Marketplace seem to be broken.

Would help to also have the link to the update site.

**Comment by JorisAerts** [comment]
Yes the plugin got unlisted in september. I've requested to list it back again, so the links will work again.
The update site is: https://raw.githubusercontent.com/JorisAerts/Eclipse-Update-Site/release/Update-Site/site.xml

In the meantime, you can install the plugin using **Help > Install New Software...**

(I've currently installed it myself like that)

**Comment by JorisAerts** [comment]
see #6
