### ISSUE TITLE
Not working on Eclipse 4.20 (Mac)

### ISSUE THREAD

**Issue by Lewox** [JorisAerts/Eclipse-Environment-Variables#15]
Hello, I have tested it on Eclipse 4.20 for Mac and it's installing correctly, but it's not displaying in preferences.

**Comment by bachden** [comment]
Same here, on Eclipse 4.21.0.
plz take a look @JorisAerts

**Comment by JorisAerts** [comment]
fixed in v1.0.0

**Comment by Lewox** [comment]
Thanks, I'll test in the latest version when I get some time.
