### ISSUE TITLE
Can not define a variable with empty value

### ISSUE THREAD

**Issue by syme31** [JorisAerts/Eclipse-Environment-Variables#3]
Test case:
1a. Leave undefined the environment variable VAR_TEST.
1b. Check the return value of `System.getenv("VAR_TEST");`
=> OK: It returned `null`.

2a. Define the environment variable VAR_TEST with the value: foo
2b. Check the return value of `System.getenv("VAR_TEST");`
=> OK: It returned the String "foo".

3a. Define the environment variable VAR_TEST with an empty value.
3b. Check the return value of `System.getenv("VAR_TEST");`
=> Not OK: It returned `null` instead of an empty String.

I'm using Eclipse 4.8 on Windows 7. Java version 1.8.0_161.

**Comment by JorisAerts** [comment]
I'm in the process of upgrading the plugin to be compatible with the latest version of Java.
I'll have a look at this issue in the meanwhile.

**Comment by JorisAerts** [comment]
This is fixed in v0.1.1
