### ISSUE TITLE
Unable to install the plugin on Spring Tool Suite 3.9.7.RELEASE

### ISSUE THREAD

**Issue by AryanVenkat** [JorisAerts/Eclipse-Environment-Variables#5]
Hi Joris,

I have been using your Eclipse extension in my earlier versions of STS (Spring Tools Suite) happily and it had been of great help to me as I didn't have to copy my custom environment variables (we have a lot of 'em) to every project I import.

But recently we have upgraded to JDK11 and STS 4 (3.9.7.RELEASE), and unfortunately here I'm not able to install your beautiful plugin. :(

I tried both ways, from the marketplace and by copying the jar to dropins, neither of 'em worked.

Here is a screenshot of the error it displays.

![image](https://user-images.githubusercontent.com/2580442/55719682-6b762600-5a1c-11e9-869c-140e0da7d01c.png)

Please help!

Thank you,
Aryan Venkat.
![image](https://user-images.githubusercontent.com/2580442/55719804-c3149180-5a1c-11e9-8b33-3ef1d51db619.png)

**Comment by JorisAerts** [comment]
see #6
