### ISSUE TITLE
Not working with eclipse 2019-06 (4.12)

### ISSUE THREAD

**Issue by bachden** [JorisAerts/Eclipse-Environment-Variables#8]
![image](https://user-images.githubusercontent.com/1224571/60026144-46ad5880-96c5-11e9-9277-e2e61d139fa6.png)
![image](https://user-images.githubusercontent.com/1224571/60026185-56c53800-96c5-11e9-9751-51fb97210817.png)

**Comment by JorisAerts** [comment]
I can't run it anymore either on 2019-06, but in the final release it doesn't show up at all anymore. I'll investigate this issue ASAP.

**Comment by bachden** [comment]
version 0.0.2 is now working with Eclipse 2019-06
