### ISSUE TITLE
Building from source throws errors

### ISSUE THREAD

**Issue by srividya-sundaram** [JorisAerts/Eclipse-Environment-Variables#9]
@JorisAerts 
I have cloned this repo and I am trying to run the plugin from source. I encountered the following 2 issues:

![env-vars](https://user-images.githubusercontent.com/8020274/72557206-2279ba80-3855-11ea-8722-602c86b22ffe.JPG)

I am using:
Eclipse IDE for Eclipse Committers : 
Version: 2019-12 (4.14.0)
Build id: 20191212-1212

adopt-openj9

Please share the steps to launch/run this plugin from source.

**Comment by JorisAerts** [comment]
This should work fine by now. Can you please check?

**Comment by JorisAerts** [comment]
I've added the JNA lib to the repo

**Comment by JorisAerts** [comment]
> @JorisAerts
> I have cloned this repo and I am trying to run the plugin from source. I encountered the following 2 issues:
> 
> ![env-vars](https://user-images.githubusercontent.com/8020274/72557206-2279ba80-3855-11ea-8722-602c86b22ffe.JPG)
> 
> I am using:
> Eclipse IDE for Eclipse Committers :
> Version: 2019-12 (4.14.0)
> Build id: 20191212-1212
> 
> adopt-openj9
> 
> Please share the steps to launch/run this plugin from source.

I've added the JNA lib to the repo
